---
  header_logo_url:
  header_logo_text: Curculionidae of the World
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about

    - label: Entiminae
      link: /otus/712818/overview
